# Generated by Django 2.1.3 on 2018-11-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_rating_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
